#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support Ruby development.
#
# Arguments:
# (None)		
#
# Version: 2.0.0
# Date: 12 Aug 2014
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-ruby-dev-ubuntu"
export COMMON_DIR="provision-ubuntu-common"

git clone "git://github.com/neopragma/$COMMON_DIR"

"./$COMMON_DIR/install_build_support"
"./$COMMON_DIR/install_sublime_text_3"
"./$COMMON_DIR/install_aptitude"
"./$COMMON_DIR/install_curl"

echo
echo '============================================================='
echo 'Installing RVM, Ruby, and Bundler...'

pushd "$HOME"
\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1
echo 'source "$HOME/.rvm/scripts/rvm"' >> .bashrc
. .bashrc
rvm --default use 2.1.1
gem install bundler
popd

echo
echo '============================================================='
echo 'Setting the desktop background image...'

mkdir -p "$HOME/.backgrounds"
cp -f ruby-background.jpg "$HOME/.backgrounds/."
gsettings set org.gnome.desktop.background picture-uri file:///home/neopragma/.backgrounds/ruby-background.jpg

./verify
