#!/bin/bash
#===============================================================================
# See if this instance appears to have everything installed as expected.
# This is for provision-java-dev-training-vm.
#
# Version: 1.1.0 
# Date: 03 May 2014
# Author: Dave Nicolette
#===============================================================================

echo
echo '============================================================='
echo 'Verifying configuration of Java development training VM...'

declare -i errors=0

declare -a pkg
pkg[${#pkg[@]}]='git'
pkg[${#pkg[@]}]='build-essential'
pkg[${#pkg[@]}]="linux-headers-$(uname -r)"
pkg[${#pkg[@]}]='dkms'
pkg[${#pkg[@]}]='python-software-properties'
pkg[${#pkg[@]}]='sublime-text-installer'

for name in "${pkg[@]}"
do
  if [[ -n "$(aptitude search ${name})" ]]; then 
      echo "package ${name} is installed"
  else
      echo "package ${name} was expected but is not installed - ERROR"
      errors="${errors}+1"
  fi 
done

source "$HOME/.rvm/scripts/rvm"
if [[ "$(rvm --version)" ]]; then
    echo "$(rvm current) is installed with rvm"
else
    echo "rvm expected but is not installed - ERROR"
    errors="${errors}+1"
fi

test "${errors}" -eq 0 && echo "...configuration is as expected." || echo "...${errors} expected package(s) or application(s) not found! Configuration may not function as desired." 
